### PR TITLE
fix verse of the day

### LINKED ISSUE #96: [BUG] Verse of the day is not appearing on home screen
### 🙁 Actual behavior

Verse of the day is not appearing for some reason.

### 🙂 Expected behavior

Verse of the day should be queried from the GraphQL API and if it exists, the given verse should be shown on the "Verse of the day" card on home screen.

Like this: https://play-lh.googleusercontent.com/VOOZ99xi2I6XiGJVMWmtuPtU3EYk_P3BVW_PggLoepkXUZUZ5E83Ww098bIHjCtAHM4=w1440-h620-rw

### 🔢 Steps to Reproduce the Problem

1. Open the app.
2. Check the home screen.

Screenshot 2021-12-29 at 9 14 27 PM

### PR DESCRIPTION
**Pull request by Gupta-Anubhav12**
Fixed, it was a type error due to which graphql gave null 
else things were fine

### CODE REVIEW

**Comment by Gupta-Anubhav12** [comment]
## so there was a typecasting issue for datetime in flutter for the graphql api,grapgql query needs date object but string was passed,
 
---

also now there is  a new issue 

### the server is at GMT and we are at GMT +5:30
so the new verse gets updated after 5:30 hours for us and till then it would show null 

a quick fix would be to show the last entered verse in db, that would change at cron job call 
this way we would get a verse of the day without a fail 

---

this is a particular issue with graphql because in the rest api we filter the verse of the day with date that's from the server's timezone and this matches the timezone of setting the verse and gives us a verse of the day without any failure. We initailly designed the db for FastApi, being REST api we are still getting full verse at the verse of the day endpoint even by saving only verseNumber without reference in db 

### fix
I am updating the qyery with last added verse in db

**Comment by Gupta-Anubhav12** [comment]
> ## so there was a typecasting issue for datetime in flutter for the graphql api,grapgql query needs date object but string was passed,
> also now there is a new issue
> 
> ### the server is at GMT and we are at GMT +5:30
> so the new verse gets updated after 5:30 hours for us and till then it would show null
> 
> a quick fix would be to show the last entered verse in db, that would change at cron job call this way we would get a verse of the day without a fail
> 
> this is a particular issue with graphql because in the rest api we filter the verse of the day with date that's from the server's timezone and this matches the timezone of setting the verse and gives us a verse of the day without any failure. We initailly designed the db for FastApi, being REST api we are still getting full verse at the verse of the day endpoint even by saving only verseNumber without reference in db
> 
> ### fix
> I am updating the qyery with last added verse in db


As another alternative we can adjust the dateTime to GMT in flutter that @ravinder-chadha  can do as I am quite new to this stuff, but I guess the last:1 works 


image

**Comment by samanyougarg** [comment]
```
query {
  allVerseOfTheDays(last: 1) {
    nodes {
      verseOrder
    }
  }
}
```

`last:1` returns an empty array so the issue is still there:
Screenshot 2021-12-30 at 7 51 06 AM

**Comment by samanyougarg** [comment]
I think we just need to add the `.toUtc()` to the datetime.now() call.

Something like this:
`var now = new DateTime.now().toUtc()`

@Gupta-Anubhav12 Try that out and see if it works.

**Comment by samanyougarg** [comment]
`var now = new DateTime.now().toUtc()` works fine. So, merging.

**Review by ravinder-chadha — COMMENTED** [review]
Yes, conversion to UTC works like a charm.

**Pull request merged**
