### PR TITLE
Feature: Rating bar function

### LINKED ISSUE #99: [FEATURE] Rating Functionality
### ⭐ Suggestion

Let's add a rating button/card on the about us page that takes the user to the Play Store page so they can give us a rating and/or review.

### 💻 Use Cases

Encourage users to give us a rating/review on the play store.

### ❌ Related Problems

_No response_

### PR DESCRIPTION
**Pull request by samanyougarg**
Rating bar implement to give rate app

### CODE REVIEW

**Comment by samanyougarg** [comment]
- [ ] Getting these errors on the console.

Screenshot 2023-01-21 at 7 33 47 PM

**Comment by samanyougarg** [comment]
- [ ] How does this work? On submitting the ratings and feedback, does it go to play store?

Screenshot 2023-01-21 at 7 34 35 PM

**Comment by jaydipgodhani** [comment]
Yes, on press submitting button user get navigate to Play Store.

**Comment by samanyougarg** [comment]
- [x] Can we not use this: https://pub.dev/packages/in_app_review

**Comment by samanyougarg** [comment]
- [ ] Clicking the star seems to redirect to the play store and not open the google review popup.

**Comment by samanyougarg** [comment]
- [ ] Also please change the star color to `#F57903`

**Pull request merged**
